spring:
  application:
    name: boiling.notification.emitter
  data:
    redis:
      timeout: 6000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:29092,localhost:39092
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:

        reactiveAutoCommit: true
        spring:
          json:
            value:
              default:
                type: com.example.await.domain.PayloadDTO
            trusted:
              packages: "*"
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: true
            trusted:
              packages: '*'
milk:
  boiling:
    redis:
      messaging:
        shards-count: 4
        stream-name: milk